#通常課題
tmp<-c(2,3,4,5,6,7,8,9)
tmp
tmp[2]<-1
tmp[8]<-3
tmp
mean(tmp)
sum(tmp)
vector<-c(tmp)
vector
sort(vector)
tmp<-rbind(c(1,2),c(3,4))
tmp
tmp<-rbind(c(1,0),c(0,1))
tmp
tmp<-matrix(c(0,1,1,0),2,2)
View(tmp)
image(tmp,col=c("black","white"))

tmp<-matrix(rep(0:1,81),9,9)
image(tmp,col=c("white","black"))

tmp<-2:9
tmp[2]<-1
tmp[8]<-3
vector<-c(sum(tmp),mean(tmp))
plot(order(tmp))
tmp_matrix<-matrix(1:4,2,2,bylow=T)
tmp_matrix[1,2]<-0
tmp_matrix[2,1]<-0
tmp_matrix[2,2]<-1
image(tmp_matrix,col=c("white","black"))
image(matrix(rep()))